sudo: required
services:
  - docker

before_install:
  - docker build -t brandonetes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brandonetes/react-test npm test

after_success:
  - docker build -t brandonetes/multi-client ./client
  - docker build -t brandonetes/multi-nginx ./nginx
  - docker build -t brandonetes/multi-server ./server
  - docker build -t brandonetes/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # takes those images and push them to docker hub
  - docker push brandonetes/multi-client
  - docker push brandonetes/multi-nginx
  - docker push brandonetes/multi-server
  - docker push brandonetes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-650336263528
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY